### PR TITLE
Add success response time

### PR DESCRIPTION
**Pull request by baterson**
Fix https://github.com/pinojs/pino-http/issues/199
Please also add "hacktoberfest-accepted" label :)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by francisdb** [comment]
Thanks @baterson

**Comment by baterson** [comment]
@francisdb you're welcome!  btw I participating in hactoberfest so if you have in mind any issues I can help with, I would glad to do it :)

**Comment by itai-gendler** [comment]
is there a reason why the response time was not added also to the customErrorMessage function?

**Pull request merged**
