### PR TITLE
Add scripts for benchmarking

### PR DESCRIPTION
**Pull request by Rauno56**
This adds couple of scripts to make running benchmarks easier.

### CODE REVIEW

**Comment by mcollina** [comment]
This is fantastic. Thanks.

**Comment by Rauno56** [comment]
Did you test it on mac? I don't have any in hand.

**Comment by mcollina** [comment]
I fixed it for the mac and pushed. I think it should work also on Linux, please check :).

**Comment by Rauno56** [comment]
K. Awesome!

**Pull request merged**
