### PR TITLE
Add support for default and name export with TypeScript and Babel

### PR DESCRIPTION
**Pull request by jarcodallo**

### CODE REVIEW

**Comment by jarcodallo** [comment]
@mcollina I added support for default.

**Comment by mcollina** [comment]
@kibertoad PTAL

**Review by kibertoad — APPROVED** [review]

**Comment by jarcodallo** [comment]
Good morning @mcollina. I think this is ready to merge :D

**Comment by kibertoad** [comment]
Let me review this quickly

**Comment by jarcodallo** [comment]
> Let me review this quickly upd: oh, wait I already did

hahaha thanks Igor

**Pull request merged**
