### PR TITLE
Move pino from dependencies to peer/dev

### PR DESCRIPTION
**Pull request by trevorr**
Fixes https://github.com/pinojs/pino-http/issues/209

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
This still support npm v6, which won't install peerdependencies by default (among other things). `peerDependencies` have always caused more headaches than the problem they solved. Maybe we can reconsider when we dump Node v12/npm v6.

**Comment by rbnayax** [comment]
Any news on the subject? This still hurts for pnpm like flat node module structure

**Comment by mcollina** [comment]
I'm really against using peerDepedencies due to the constant problem they cause.

**Comment by jsumners** [comment]
Same.

**Pull request closed without merging**
