### PR TITLE
fix(genreqid): add param for server response

### LINKED ISSUE #250: GenReqId interface does not have `res` specified resulting in typescript error
GenReqId interface does not have `res` specified resulting in typescript error

_Originally posted by @MrTalon63 in https://github.com/pinojs/pino-http/issues/240#issuecomment-1250154095_

### PR DESCRIPTION
**Pull request by Eji4h**
fix #250

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you add an assertion using tsd?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Eji4h** [comment]
Can you add "hacktoberfest-accepted" label? @mcollina

**Pull request merged**
