### PR TITLE
Replace travis.ci with Github Actions

### LINKED ISSUE #91: Migrate to Github Actions
As titled

### PR DESCRIPTION
**Pull request by gkampitakis**
Close #91

### CODE REVIEW

**Comment by gkampitakis** [comment]
Updated the action to use the same pattern as other packages of pino using actions

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Would you mind to send a PR to update the README badge as well?

**Comment by gkampitakis** [comment]
> Would you mind to send a PR to update the README badge as well?

Happy to.

**Pull request merged**
